// Globally diverse bot names to make ranked games feel like real multiplayer
// Emphasis on South Asian (Nepal, India) names, plus Africa, East Asia, Middle East, Latin America, Europe
const BOT_NAMES = [
  // Nepal
  "Aarav Sharma",
  "Sita Adhikari",
  "Bijay Thapa",
  "Anisha Gurung",
  "Rajesh Shrestha",
  "Priya Poudel",
  "Sujan Tamang",
  "Nisha Karki",
  "Dipesh Bhandari",
  "Manisha Rai",
  "Roshan Maharjan",
  "Sarita Lama",
  "Bikash Khadka",
  "Sunita Magar",
  "Prajwal Dahal",
  "Kriti Basnet",
  "Aashish Koirala",
  "Srijana Pandey",
  "Nabin Ghimire",
  "Roshni Sapkota",
  "Sandesh Bhattarai",
  "Alisha Chhetri",
  "Rajan Pokharel",
  "Binita Joshi",
  "Umesh Devkota",

  // India
  "Arjun Patel",
  "Sneha Reddy",
  "Vikram Iyer",
  "Priyanka Nair",
  "Rohit Mehta",
  "Kavitha Subramaniam",
  "Harsh Agarwal",
  "Deepika Chauhan",
  "Anil Verma",
  "Neha Deshpande",
  "Siddharth Jha",
  "Meera Kulkarni",
  "Ravi Krishnan",
  "Pooja Gupta",
  "Karthik Rajan",

  // Africa
  "Amara Okafor",
  "Kwame Mensah",
  "Fatima Diallo",
  "Tendai Moyo",
  "Chiamaka Eze",
  "Kofi Asante",
  "Zainab Bello",
  "Thabo Ndlovu",
  "Aisha Mwangi",
  "Yemi Adeyemi",
  "Lamine Toure",
  "Nkechi Obi",
  "Sekou Diarra",
  "Amina Traore",
  "Chidi Nwachukwu",

  // East Asia
  "Yuki Tanaka",
  "Wei Zhang",
  "Soo-Jin Park",
  "Hiro Nakamura",
  "Mei Lin Chen",
  "Jun-Ho Kim",
  "Sakura Yamamoto",
  "Li Wei",
  "Min-Jae Lee",
  "Aoi Suzuki",
  "Xin Zhao",
  "Hana Watanabe",
  "Jian Liu",
  "Yuna Choi",
  "Takeshi Ito",

  // Middle East
  "Omar Hassan",
  "Layla Al-Farsi",
  "Yusuf Khalil",
  "Noor Aziz",
  "Tariq Mansour",
  "Sara Hussain",
  "Kareem El-Din",
  "Fatimah Sayeed",
  "Adel Rashid",
  "Hanan Bakri",
  "Faisal Nasser",
  "Rania Qadir",
  "Ibrahim Jaber",
  "Dina Sabbagh",
  "Mustafa Hakim",

  // Latin America
  "Diego Fernandez",
  "Camila Rojas",
  "Mateo Rivera",
  "Valentina Cruz",
  "Andrés Morales",
  "Isabella Vargas",
  "Santiago Herrera",
  "Luciana Torres",
  "Carlos Mendoza",
  "Sofía Castillo",
  "Juan Pablo Rios",
  "Daniela Fuentes",
  "Miguel Sánchez",
  "Gabriela Paredes",
  "Alejandro Vega",

  // Europe
  "Liam O'Brien",
  "Emma Larsson",
  "Nikolai Petrov",
  "Chiara Rossi",
  "Maximilian Weber",
  "Élise Dubois",
  "Oleksandr Koval",
  "Ingrid Hansen",
  "Tomas Novak",
  "Katarina Jovic",
  "Dimitris Papadopoulos",
  "Freya Andersen",
  "Mateusz Kowalski",
  "Beatrice Moretti",
  "Hugo Bergström",

  // Southeast Asia
  "Anh Nguyen",
  "Putri Wulandari",
  "Somchai Phan",
  "Maria Santos",
  "Rizal Ismail",
  "Thanh Le",
  "Dewi Kartika",
  "Arnel Reyes",
  "Linh Tran",
  "Budi Santoso",
];

// Get a random bot name
export function getRandomBotName(): string {
  return BOT_NAMES[Math.floor(Math.random() * BOT_NAMES.length)];
}

// Generate a consistent bot name based on seed (for reproducibility)
export function generateBotName(seed: number): string {
  const index = Math.abs(seed) % BOT_NAMES.length;
  return BOT_NAMES[index];
}
